web:
  image: nginx
  volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - ./photos:/var/www/files
    - ./dist:/var/www/html
    - ./.htpasswd:/var/www/.htpasswd
  ports:
    - '8080:80'
  environment:
    - NGINX_PORT=80
